apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webapps
  name: app-role
rules:
- apiGroups: 
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io 
  resources:
    - pods
    - componentstatuses
    - configmap
    - daemonsets
    - deployments
    - events
    - endpoints 
    - horizontalpodautoscalers
    - ingress 
    - jobs 
    - limitranges
    - namespaces
    - nodes
    - pods 
    - persistentvolumes
    - persistentvolumeclaim 
    - resourcequotas
    - replicasets
    - replicationcontrollers
    - serviceaccounts
    - services

  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

